# @package _group_
# (mgc, lf0, vuv, bap)
stream_sizes: [60, 1, 1, 5]
has_dynamic_features: [false, false, false, false]
num_windows: 1
# If None, automatically set based on stream sizes
stream_weights:

netG:
  _target_: nnsvs.model.RMDN
  in_dim: 424
  out_dim: 67
  hidden_dim: 256
  num_layers: 2
  dropout: 0.1
  bidirectional: true
  num_gaussians: 2
