# @package _group_
# (mgc, lf0, vuv, bap)
stream_sizes: [60, 1, 1, 5]
has_dynamic_features: [false, false, false, false]
num_windows: 1
# NOTE: seems like giving a large weight to the F0 stream is important
# when we don't use delta and deltadelta features.
stream_weights: [1.0, 1.0, 1.0, 1.0]

netG:
  _target_: nnsvs.model.Conv1dResnetSAR
  in_dim: 299
  out_dim: 67
  hidden_dim: 64
  num_layers: 6
  dropout: 0.0

  stream_sizes: [1, 59, 1, 1, 5]
  ar_orders: [200, 20, 200, 20, 20]
