# General settings.
spk: "jsut"

# exp tag(for managing experiments)
tag:

###########################################################
#                DATA PREPARATION SETTING                 #
###########################################################


###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################

# HTS-style question used for extracting musical/linguistic context from musicxml files
question_path: "../../_common/hed/jp_qst001_nnsvs.hed"

timelag_features: defaults
duration_features: defaults
acoustic_features: static_deltadelta

###########################################################
#                TRAINING SETTING                         #
###########################################################

# Models
# To customize, put your config in conf/train/model/ and
# specify the config name below
timelag_model: timelag_ffn
duraiton_model: duration_lstm
acoustic_model: acoustic_conv

# Pretrained model dir (leave empty to disable)
pretrained_expdir:
# batch size
batch_size: 4

###########################################################
#                SYNTHESIS SETTING                        #
###########################################################
timelag_synthesis: defaults
duration_synthesis: defaults
acoustic_synthesis: defaults

# latest.pth, best_loss.pth or ${checkpoint_name}.pth
eval_checkpoint: latest.pth
