# General settings.
spk: "yoko"

# exp tag(for managing experiments)
tag:

###########################################################
#                DATA PREPARATION SETTING                 #
###########################################################

# Directory of Unzipped singing voice database
# PLEASE CHANGE THE PATH BASED ON YOUR ENVIRONMENT
db_root: "downloads/HTS-demo_NIT-SONG070-F001"

# Output directory
out_dir: "./data"

###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################

# HTS-style question used for extracting musical/linguistic context from musicxml files
question_path: "../../_common/hed/jp_qst001_nnsvs.hed"

timelag_features: defaults
duration_features: defaults
acoustic_features: static_deltadelta

###########################################################
#                TRAINING SETTING                         #
###########################################################

# Models
# To customize, put your config in conf/train/model/ and
# specify the config name below
timelag_model: timelag_mdn
duraiton_model: duration_mdn
acoustic_model: acoustic_mdn

# Pretrained model dir (leave empty to disable)
pretrained_expdir:
# batch size
batch_size: 8

###########################################################
#                SYNTHESIS SETTING                        #
###########################################################
timelag_synthesis: defaults
duration_synthesis: defaults
acoustic_synthesis: defaults

# latest.pth or best.pth
eval_checkpoint: latest.pth