# coding: utf-8
defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - timelag: defaults
  - duration: defaults
  - acoustic: defaults
  - nsf: defaults    
verbose: 100

device: cuda # or cpu

# Only the combination of utt_list and in_dir input is supported
utt_list:
in_dir:
out_dir:
  
sample_rate: 16000
frame_period: 5
question_path: path/to/qst.hed
log_f0_conditioning: true

# Use ground truth duration or not
# if true, time-lag and duration models will not be used.
ground_truth_duration: false

gain_normalize: false

# If not empty, try to search statisics in the directory
stats_dir:
# If not empty, try to search models in the directory
model_dir:
model_checkpoint: latest.pth
