# @package _group_

stream_sizes: [1]
has_dynamic_features: [false]
stream_weights: [1]

netG:
  _target_: nnsvs.model.Conv1dResnetMDN
  in_dim: 299
  out_dim: 199
  hidden_dim: 256
  num_layers: 6
  dropout: 0.1
  num_gaussians: 4
  dim_wise: true
