# @package _global_

defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - nsf: defaults
    
verbose: 100

data:
  #training set
  train_no_dev:
    list_path: data/list/train_no_dev.list
  #development set
  dev:
    list_path: data/list/dev.list
  #evaluation set
  eval:
    list_path: data/list/eval.list
